apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: direction-watch
  name: direction-watch
spec:
  containers:
    - image: yuitta/cloud-tools:latest
      imagePullPolicy: Always
      name: direction-watch (change Pod name if need)
      resources: {}
      volumeMounts:
        - mountPath: "/mnt"
          name: task-pv-storage
      command:
        - sh
        - -c
        - sleep infinity
  volumes:
    - name: task-pv-storage
      persistentVolumeClaim:
        claimName: test-op-pvc (change ClaimName to your pvc name)
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}